### ISSUE TITLE
Problem with beta 5 of XCode

### ISSUE THREAD

**Issue by JulienBreux** [haoyuche/IOSCalendarView#1]
Just a quick question:

Do you have this pb:

```
/tmp/IOSCalendarView/CalendarView/ViewController.swift:36:24: Cannot invoke 'requestAccessToEntityType' with an argument list of type '(EKEntityType, completion: (Bool, NSError?) -> Void)'
```

With the `Version 7.0 beta 5 (7A176x)` of XCode?

Thx

**Comment by haoyuche** [comment]
It is because apple keeps changing its APIs before swift2 release.
The function now is change to completion: (ObjBool, NSError?) I think.
You need to check the arguments types from Apple Swift Lib every time.
